const icons = {
 home:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
 chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2V11.5a9.5 9.5 0 0 1 19 0Z"/><path d="M7 10h10M7 14h6"/>',
 box:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V8M12 13v10M7 5.8l9 5"/>',
 order:'<rect x="5" y="4" width="14" height="18" rx="2"/><path d="M9 4V2h6v2M9 10h6M9 14h6M9 18h4"/>',
 doc:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6ZM14 2v6h6M8 13h8M8 17h6"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',
 arrow:'<path d="m9 5 7 7-7 7"/>',up:'<path d="M12 19V5m-6 6 6-6 6 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',
 spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',logout:'<path d="M9 4H4v16h5m6-12 4 4-4 4M8 12h11"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.doc}</svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => `${Number(n).toLocaleString('ko-KR')}원`;
const date = n => new Date(n).toLocaleDateString('ko-KR');
const pages = {home:['대시보드','home'],chat:['AI 어시스턴트','chat'],products:['상품 둘러보기','box'],orders:['내 주문','order'],documents:['지식 문서','doc'],about:['프로젝트 소개','code'],profile:['내 정보','user']};
let token = sessionStorage.getItem('moa-token') || '';
let member = null;
let page = '';
let generation = 0;
let chatPending = false;
let chatHistoryLoading = false;
let currentMessages = [];
let productSearchGeneration = 0;
const app = document.querySelector('#app');
const dialog = document.querySelector('#dialog');
let toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',4000)}
async function api(path,{method='GET',body,timeout=20000}={}){
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);
 try{const res=await fetch(path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});
 const data=await res.json().catch(()=>({}));
 if(!res.ok){if(res.status===401){token='';member=null;currentMessages=[];sessionStorage.removeItem('moa-token')}const translations={'Invalid email or password':'이메일 또는 비밀번호를 확인해 주세요.','Email already registered':'이미 가입한 이메일이에요. 로그인으로 이어갈 수 있어요.','Insufficient stock':'재고가 부족해요. 수량을 줄여 주세요.','Product not found':'상품을 찾을 수 없어요.'};throw new Error(res.status===401?'로그인이 필요해요. 이메일과 비밀번호를 확인해 주세요.':translations[data.detail]||(typeof data.detail==='string'?data.detail:res.status===422?'입력한 값의 형식과 범위를 확인해 주세요.':'요청을 처리하지 못했어요. 잠시 후 다시 시도해 주세요.'))}return data;
 }catch(e){if(e.name==='AbortError')throw new Error('응답이 늦어지고 있어요. 처리 결과를 확인한 뒤 다시 시도해 주세요.');if(e instanceof TypeError)throw new Error('서버에 연결하지 못했어요. API 서버 실행 상태를 확인한 뒤 다시 시도해 주세요.');throw e}finally{clearTimeout(timer)}
}
const loading = '<div class="loader" role="status" aria-label="불러오는 중"><i></i><i></i><i></i></div>';
const empty=(title,description,action='')=>`<div class="empty">${icon('box')}<h3>${title}</h3><p>${description}</p>${action}</div>`;
function errorBox(e){return `<div class="notice error" role="alert"><span>${esc(e.message)}</span><button class="btn small" data-action="refresh">다시 불러오기</button></div>`}
function heading(kicker,title,sub,action=''){return `<div class="heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="subtitle">${sub}</p></div>${action}</div>`}
function requireLogin(){return empty('로그인하면 이어서 이용할 수 있어요','내 주문과 대화는 로그인한 계정에 연결돼요.','<button class="btn primary" data-action="login">로그인하기</button>')}
function shell(){app.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">${icon('spark')}</span>모아</a><p class="workspace-label">AI WORKSPACE</p><p class="nav-label">워크스페이스</p><nav class="nav" aria-label="주 메뉴">${Object.entries(pages).filter(([key])=>key!=='profile').map(([key,[label,i]])=>`<a href="#${key}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="mini-note"><strong>궁금한 건, 한곳에서</strong>주문부터 정책까지<br>AI와 대화하며 확인해요.</div><button class="account" data-action="${member?'profile':'login'}"><span class="avatar">${icon('user')}</span><span>${esc(member?.name || (member?'내 계정':'게스트'))}<small>${member?'내 계정 관리':'로그인하고 시작해요'}</small></span>${icon('arrow')}</button></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">워크스페이스 <span>/</span> <strong>${pages[page][0]}</strong></div><button class="status" data-action="${member?'profile':'login'}"><span class="dot"></span>${member?esc(member.name||member.email):'로그인 전'}</button></header><div class="content" id="content"></div></main></div>`}
async function render(){const id=++generation;page=location.hash.slice(1);if(!pages[page])page='home';shell();const content=document.querySelector('#content');const put=html=>{if(id===generation)content.innerHTML=html};
 if(page==='home'){
 put(`${heading('나의 AI 워크스페이스','일상이 가벼워지는 곳, 모아','필요한 정보와 업무를 한곳에서 연결해요.')}<section class="hero"><div><h2>궁금했던 것들,<br>이제 대화로 해결해요</h2><p>내 주문 확인부터 배송·환불 정책까지.<br>대화로 필요한 정보를 확인해요.</p><a class="btn primary" href="#chat">AI와 대화하기 ${icon('arrow')}</a></div><div class="hero-art" aria-hidden="true"><div class="orb"><span class="eye"></span><span class="eye"></span></div><span class="spark">${icon('spark')}</span><span class="art-chip">무엇이 궁금하세요?</span></div></section><div class="stats"><div class="stat"><div><label>등록된 상품</label><strong id="count-products">—</strong></div><span class="icon-box">${icon('box')}</span></div><div class="stat"><div><label>나의 주문</label><strong id="count-orders">${member?'—':'로그인 전'}</strong></div><span class="icon-box">${icon('order')}</span></div><div class="stat"><div><label>지식 문서</label><strong id="count-documents">—</strong></div><span class="icon-box">${icon('doc')}</span></div></div><div class="grid-two"><section class="card"><div class="section-title"><h2>어떤 도움이 필요하세요?</h2><span class="tag">빠른 시작</span></div>${[['chat','chat','내 주문이 궁금해요','AI에게 주문 내역을 물어볼 수 있어요'],['products','box','상품을 둘러볼래요','상품을 검색하고 바로 주문해요'],['documents','doc','AI가 참고할 문서를 관리해요','배송, 교환, 환불 정책을 등록해요']].map(([p,i,title,sub])=>`<a class="quick-row" href="#${p}"><span class="icon-box">${icon(i)}</span><span class="row-body"><strong>${title}</strong><small>${sub}</small></span>${icon('arrow')}</a>`).join('')}</section><section class="card"><div class="section-title"><h2>모아는 이렇게 도와줘요</h2><a class="text-link" href="#about">자세히 ${icon('arrow')}</a></div>${[['질문의 의도를 이해해요','주문, 회원 정보, 정책 질문을 구분해요.'],['필요한 정보를 찾아요','내 정보 또는 등록한 지식 문서를 확인해요.'],['이해하기 쉽게 답해요','찾은 정보를 바탕으로 자연스럽게 설명해요.']].map(([t,s],i)=>`<div class="flow-row"><span class="step">${i+1}</span><div><strong>${t}</strong><p>${s}</p></div></div>`).join('')}</section></div><p class="footnote">정보를 찾는 시간은 줄이고, 중요한 일에 집중해요.</p>`);
 const requests=[['products','/products','개'],['documents','/documents','개'],...(member?[['orders','/orders/me','건']]:[])];await Promise.all(requests.map(async([key,url,unit])=>{try{const rows=await api(url);if(id===generation)document.querySelector(`#count-${key}`).innerHTML=`${rows.length}<small>${unit}</small>`}catch{if(id===generation){const el=document.querySelector(`#count-${key}`);el.textContent='연결 확인';el.style.fontSize='16px';el.title='API 서버 연결 상태를 확인해 주세요.'}}}));return;
 }
 if(page==='about'){put(about());return}
 if(page==='chat'){put(chatView());if(currentMessages.length){document.querySelector('#messages').innerHTML=currentMessages.map(m=>messageHTML(m.role,m.text)).join('');scrollChat()}return}
 if(page==='products'){put(`${heading('상품','필요한 상품을 찾아요','이름과 카테고리로 원하는 상품을 검색해요.','<button class="btn" data-action="add-product">'+icon('plus')+' 상품 등록</button>')}<form id="search-form" class="filters"><input name="name" aria-label="상품명" placeholder="어떤 상품을 찾으세요?"><input name="category" aria-label="카테고리" placeholder="카테고리"><button class="btn primary" type="submit">${icon('search')}검색</button></form><div id="product-list">${loading}</div>`);await loadProducts();return}
 if(page==='orders'){put(heading('주문','내 주문을 한눈에 확인해요','이 계정에서 주문한 내역을 모았어요.')+(member?`<div id="orders">${loading}</div>`:requireLogin()));if(!member)return;try{const rows=await api('/orders/me');const products=await api('/products').catch(()=>[]);put(heading('주문','내 주문을 한눈에 확인해요','이 계정에서 주문한 내역을 모았어요.')+(!rows.length?`<section class="card">${empty('아직 주문 내역이 없어요','상품을 둘러보고 첫 주문을 시작해요.','<a class="btn primary" href="#products">상품 둘러보기</a>')}</section>`:`<section class="card table-wrap"><table><thead><tr><th>주문 번호</th><th>상품</th><th>수량</th><th>주문일</th></tr></thead><tbody>${rows.slice().reverse().map(o=>`<tr><td>#${o.id}</td><td>${esc(products.find(p=>p.id===o.product_id)?.name||`상품 #${o.product_id}`)}</td><td>${o.quantity}개</td><td>${date(o.created_at)}</td></tr>`).join('')}</tbody></table></section>`))}catch(e){put(heading('주문','주문 내역을 불러오지 못했어요','연결을 확인하고 다시 시도할 수 있어요.')+errorBox(e))}return}
 if(page==='documents'){put(`${heading('지식 베이스','AI의 지식을 채워요','등록한 문서는 배송·교환·환불 정책 답변에 활용돼요.','<button class="btn primary" data-action="add-document">'+icon('plus')+' 문서 추가</button>')}<div id="documents">${loading}</div>`);try{const rows=await api('/documents');if(id!==generation)return;document.querySelector('#documents').innerHTML=`<section class="card"><div class="section-title"><h2>등록된 문서 <span class="tag">${rows.length}개</span></h2><span class="tag">AI 검색에 활용</span></div>${rows.length?rows.map((d,i)=>`<article class="document-row"><div class="document-meta"><strong>문서 ${i+1}</strong><button class="btn small" data-action="edit-document" data-id="${esc(d.id)}">수정하기</button></div><p>${esc(d.content)}</p><div class="document-meta"><code>${esc(d.id)}</code></div></article>`).join(''):empty('아직 등록된 문서가 없어요','정책 문서를 추가하면 AI가 참고할 수 있어요.')}</section>`;document.querySelectorAll('[data-action="edit-document"]').forEach(button=>button.onclick=()=>documentModal(rows.find(d=>d.id===button.dataset.id)))}catch(e){if(id===generation)document.querySelector('#documents').innerHTML=errorBox(e)}return}
 if(page==='profile'){put(heading('계정','내 정보를 확인해요','로그인한 계정에 연결된 정보예요.')+(member?`<section class="card profile">${[['이름',member.name||'등록하지 않았어요'],['이메일',member.email],['나이',member.age==null?'등록하지 않았어요':`${member.age}세`],['가입일',date(member.created_at)]].map(([k,v])=>`<div class="profile-row"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}<button class="btn" data-action="logout" style="margin-top:24px">${icon('logout')}로그아웃</button></section>`:requireLogin()))}
}
async function loadProducts(query=''){const searchId=++productSearchGeneration;const target=document.querySelector('#product-list');if(!target)return;target.innerHTML=loading;try{const rows=await api('/products'+query);if(!target.isConnected||searchId!==productSearchGeneration)return;target.innerHTML=rows.length?`<div class="products">${rows.map(p=>`<article class="card product-card"><div class="product-visual">${icon('box')}</div><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p class="price">${money(p.price)}</p><p class="stock">${p.stock>0?`재고 ${p.stock}개`:'품절되었어요'}</p><button class="btn" data-id="${p.id}" data-action="order" ${p.stock<=0?'disabled':''}>상품 상세 보기 ${icon('arrow')}</button></article>`).join('')}</div>`:empty('조건에 맞는 상품이 없어요','검색어를 바꾸거나 새 상품을 등록할 수 있어요.');}catch(e){if(target.isConnected&&searchId===productSearchGeneration)target.innerHTML=errorBox(e)}}
function messageHTML(role,text){return `<div class="message ${role}"><small>${role==='user'?'나':'모아'}</small><div class="bubble">${esc(text)}</div></div>`}
function scrollChat(){const box=document.querySelector('#messages');if(box)box.scrollTop=box.scrollHeight}
function chatView(){return `${heading('AI 어시스턴트','무엇이 궁금하세요?','내 주문부터 이용 정책까지, 대화로 확인해요.')}<div id="chat-error"></div><div class="chat-layout"><section class="chat-panel"><div class="chat-header"><span class="brand-mark">${icon('spark')}</span><div>모아 어시스턴트<small>내 정보와 지식 문서를 연결해요</small></div>${member?'<button class="btn small" style="margin-left:auto" data-action="chat-history">이전 기록</button>':''}</div><div class="chat-messages" id="messages" role="log" aria-live="polite"><div class="chat-welcome"><span class="brand-mark">${icon('spark')}</span><h2>복잡한 검색 대신, 가벼운 대화</h2><p>궁금한 내용을 편하게 남겨 주세요.</p><div class="suggestions">${['내 주문 내역 알려줘','환불 정책이 궁금해','내 회원 정보 알려줘'].map(s=>`<button class="suggestion" data-prompt="${s}">${s}${icon('arrow')}</button>`).join('')}</div></div></div>${member?'':`<p class="subtitle" style="text-align:center;font-size:12px;margin-bottom:12px">대화를 보내려면 <button data-action="login" style="text-decoration:underline">로그인</button>이 필요해요.</p>`}<form class="composer" id="chat-form"><input name="message" maxlength="4000" aria-label="메시지" placeholder="궁금한 내용을 입력해 주세요" autocomplete="off" required><button class="btn primary" aria-label="메시지 보내기" ${chatPending||chatHistoryLoading?'disabled':''}>${icon('up')}</button></form></section><aside class="chat-aside"><section class="card aside-card"><span class="icon-box">${icon('spark')}</span><h3 style="margin-top:18px">이런 걸 물어볼 수 있어요</h3><p>주문 내역과 주문 수량<br>배송·교환·환불 정책<br>내 계정에 등록된 정보</p></section><section class="card aside-card"><h3>대화는 이어져요</h3><p>로그인 후에는 빈 화면에서 시작해요. 저장된 대화는 이전 기록에서 따로 확인할 수 있어요. 정책 답변은 계정의 이전 대화를 참고할 수 있어요.</p></section><p class="subtitle" style="font-size:11px;padding:0 12px">AI 답변에는 오류가 있을 수 있어요.<br>중요한 내용은 원본 정보와 함께 확인해 주세요.</p></aside></div>`}
async function sendChat(text){if(!member){authModal();return}if(chatPending||chatHistoryLoading||!text.trim())return;chatPending=true;const accountToken=token;const box=document.querySelector('#messages');if(box.querySelector('.chat-welcome'))box.innerHTML='';currentMessages.push({role:'user',text});box.insertAdjacentHTML('beforeend',messageHTML('user',text));const wait=document.createElement('div');wait.innerHTML=loading;box.append(wait);const form=document.querySelector('#chat-form');form.querySelector('button').disabled=true;form.message.value='';scrollChat();try{const result=await api('/chats',{method:'POST',body:{message:text},timeout:180000});if(token===accountToken){currentMessages.push({role:'assistant',text:result.response});}if(token===accountToken&&box.isConnected){wait.remove();box.insertAdjacentHTML('beforeend',messageHTML('assistant',result.response));scrollChat()}}catch(e){if(box.isConnected){wait.remove();const error=document.createElement('p');error.className='form-error';error.setAttribute('role','alert');error.textContent=e.message;box.append(error);form.message.value=text}}finally{chatPending=false;document.querySelector('#chat-form button')?.removeAttribute('disabled')}}
async function showChatHistory(){
 if(!member)return;
 const accountToken=token;
 dialog.innerHTML=`<div class="dialog-top"><h2 id="dialog-title">이전 대화 기록</h2><button type="button" aria-label="닫기">${icon('close')}</button></div><p class="subtitle">이 계정에 저장된 최근 100개 기록이에요. 당시 답변으로, 현재 회원 정보와 다를 수 있어요.</p><div id="history-records">${loading}</div>`;
 dialog.querySelector('button').onclick=()=>dialog.close();
 dialog.showModal();
 const target=dialog.querySelector('#history-records');
 try{
  const rows=await api('/chats/me');
  if(!target.isConnected||token!==accountToken)return;
  target.innerHTML=rows.length?rows.map(row=>`<article class="history-record"><small>${esc(new Date(row.created_at).toLocaleString('ko-KR'))}</small>${messageHTML('user',row.request)}${messageHTML('assistant',row.response)}</article>`).join(''):empty('저장된 대화가 없어요','대화를 보내면 이곳에서 다시 확인할 수 있어요.');
 }catch(e){if(target.isConnected)target.innerHTML=`<p class="form-error" role="alert">${esc(e.message)}</p>`}
}
function openModal(title,sub,fields,submitLabel,onSubmit,footer=''){dialog.innerHTML=`<div class="dialog-top"><h2 id="dialog-title">${title}</h2><button type="button" data-close aria-label="닫기">${icon('close')}</button></div><p class="subtitle">${sub}</p><form id="modal-form">${fields}<p class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" class="btn" data-close>취소</button><button class="btn primary" type="submit">${submitLabel}</button></div></form>${footer}`;if(!dialog.open)dialog.showModal();dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const btn=form.querySelector('[type="submit"]');btn.disabled=true;form.querySelector('.form-error').textContent='';try{await onSubmit(new FormData(form));}catch(err){form.querySelector('.form-error').textContent=err.message}finally{btn.disabled=false}}}
const field=(label,name,type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" ${extra} required></label>`;
function authModal(signup=false){openModal(signup?'모아와 함께 시작해요':'다시 만나서 반가워요',signup?'계정을 만들면 주문과 대화를 이어갈 수 있어요.':'이메일로 로그인하고 나의 워크스페이스를 열어요.',`${signup?field('이름','name','text','maxlength="100" autocomplete="name"'):''}${field('이메일','email','email','autocomplete="email"')}${field('비밀번호','password','password',`autocomplete="${signup?'new-password':'current-password'}" maxlength="72"`)}`,signup?'가입하고 시작하기':'로그인하기',async data=>{const body=Object.fromEntries(data);if(signup)await api('/members/signup',{method:'POST',body});const result=await api('/members/login',{method:'POST',body:{email:body.email,password:body.password}});token=result.access_token;sessionStorage.setItem('moa-token',token);member=await api('/members/me');currentMessages=[];dialog.close();toast('로그인했어요.');render()},`<button type="button" id="auth-switch" style="width:100%;margin-top:16px;font-size:13px;color:var(--muted)">${signup?'이미 계정이 있어요 · 로그인':'처음 오셨나요? · 회원가입'}</button>`);document.querySelector('#auth-switch').onclick=()=>authModal(!signup)}
function productModal(){if(!member){authModal();return}openModal('새 상품을 등록해요','상품 정보를 입력하면 목록에서 바로 확인할 수 있어요.',field('상품명','name','text','maxlength="200"')+field('카테고리','category','text','maxlength="100"')+field('가격 (원)','price','number','min="0" step="1"')+field('재고 수량','stock','number','min="0" step="1"'),'상품 등록하기',async data=>{await api('/products',{method:'POST',body:{name:data.get('name').trim(),category:data.get('category').trim(),price:Number(data.get('price')),stock:Number(data.get('stock'))}});dialog.close();toast('상품을 등록했어요.');render()})}
async function orderModal(id){try{const p=await api(`/products/${id}`);openModal(esc(p.name),`${esc(p.category)} · 재고 ${p.stock}개`,`<p class="price">${money(p.price)}</p>${field('주문 수량','quantity','number',`min="1" max="${p.stock}" step="1" value="1"`)}<p class="subtitle" id="total">총 ${money(p.price)}</p>`,'주문하기',async data=>{if(!member){authModal();return}await api('/orders',{method:'POST',body:{product_id:p.id,quantity:Number(data.get('quantity'))}});dialog.close();toast('주문이 완료됐어요.');location.hash='orders'});dialog.querySelector('[name="quantity"]').oninput=e=>{document.querySelector('#total').textContent=`총 ${money(p.price*Number(e.target.value))}`}}catch(e){toast(e.message)}}
function documentModal(doc){openModal(doc?'지식 문서를 수정해요':'새 지식 문서를 추가해요','배송·환불 정책처럼 AI가 참고할 내용을 입력해 주세요.',`<label class="field">문서 내용<textarea name="text" required maxlength="30000" placeholder="예: 상품을 받은 날부터 7일 안에 교환을 신청할 수 있어요.">${esc(doc?.content||'')}</textarea></label>`,doc?'수정 내용 저장하기':'문서 추가하기',async data=>{const text=data.get('text').trim();if(!text)throw new Error('문서 내용을 입력해 주세요.');await api(doc?`/documents/${encodeURIComponent(doc.id)}`:'/documents',{method:doc?'PUT':'POST',body:doc?{text}:{texts:[text]},timeout:120000});dialog.close();toast('지식 문서를 저장했어요.');render()})}
function about(){return `${heading('프로젝트 소개','API에서 대화형 서비스로','이 프로젝트에 담긴 기능과 기술을 살펴봐요.')}<section class="hero"><div><span class="tag blue" style="margin-bottom:16px">AI Agent Project</span><h2>흩어진 정보를 연결하는<br>나만의 AI 워크스페이스</h2><p style="margin:0">회원·상품·주문 API에 검색 증강 생성과 대화 기억을 연결했어요.<br>이제 화면에서 직접 기능을 사용할 수 있어요.</p></div><div class="hero-art" aria-hidden="true"><div class="orb">${icon('code')}</div></div></section><div class="stack-grid">${[['code','FastAPI · SQLAlchemy','서비스 API','회원 가입과 JWT 인증, 상품 등록, 주문 생성과 조회를 처리해요.'],['chat','Ollama · LangChain','AI 대화','질문의 의도를 분류하고 주문 조회, 회원 정보, 정책 검색으로 연결해요.'],['search','PostgreSQL · pgvector','지식 검색','문서를 임베딩하고 pgvector 유사도 검색으로 관련 정책을 찾아요. BM25·RRF 보조 함수도 갖추고 있어요.'],['doc','대화 기록 · PostgreSQL','문맥 기억','사용자별 대화를 저장하고 정책 답변을 생성할 때 이전 문맥을 참고해요.'],['spark','Redis Stack','시맨틱 캐시','유사 질문 캐시 모듈을 갖추고 있어요. 현재 대화 API에서는 답변 재사용을 중단했어요.'],['home','Langfuse · LoRA','관찰과 모델 튜닝','LLM 호출을 추적하고, sLLM 분류를 위한 LoRA 학습 스크립트를 갖추고 있어요.']].map(([i,t,h,p])=>`<article class="card"><span class="icon-box">${icon(i)}</span><h3>${h}</h3><span class="tag">${t}</span><p>${p}</p></article>`).join('')}</div><section class="card"><h2>질문이 답변이 되기까지</h2><div class="architecture"><span>질문 입력</span>${icon('arrow')}<span>사용법 안내 · 의도 분류</span>${icon('arrow')}<span>주문 / 회원 / 정책 조회</span>${icon('arrow')}<span>AI 답변 · 대화 저장</span></div><p class="subtitle" style="font-size:13px">사용법은 검증된 안내로, 주문·회원 정보는 현재 조회 결과로 답해요. 정책 질문은 검색한 문서와 이전 문맥을 활용해요.</p></section><p class="footnote">프론트엔드: HTML · CSS · JavaScript / FastAPI에서 같은 주소로 제공해요.</p>`}
app.addEventListener('click',e=>{const prompt=e.target.closest('[data-prompt]');if(prompt){sendChat(prompt.dataset.prompt);return}const b=e.target.closest('[data-action]');if(!b)return;const actions={'chat-history':showChatHistory,login:()=>authModal(),logout:()=>{token='';member=null;currentMessages=[];sessionStorage.removeItem('moa-token');toast('로그아웃했어요.');render()},profile:()=>location.hash='profile',refresh:()=>render(),'add-product':productModal,'add-document':()=>documentModal(),order:()=>orderModal(b.dataset.id)};actions[b.dataset.action]?.()});
app.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();const data=new FormData(e.target);const params=new URLSearchParams();for(const [k,v]of data)if(v.trim())params.set(k,v.trim());loadProducts(params.size?'?'+params:'')}if(e.target.id==='chat-form'){e.preventDefault();sendChat(e.target.message.value.trim())}});
window.addEventListener('hashchange',render);
if(token){try{member=await api('/members/me')}catch{token='';sessionStorage.removeItem('moa-token')}}
render();
