import json

# 분류 레이블: get_my_orders / get_my_profile / get_policy
# instruction: 사용자 질문, response: 분류 결과
examples = [
    # ── get_my_orders ────────────────────────────────────────────
    {"instruction": "내 주문 내역 보여줘", "response": "get_my_orders"},
    {"instruction": "내가 주문한 거 뭐 있어?", "response": "get_my_orders"},
    {"instruction": "주문 목록 확인하고 싶어", "response": "get_my_orders"},
    {"instruction": "최근 주문 뭐 했지?", "response": "get_my_orders"},
    {"instruction": "내 주문 상태 알려줘", "response": "get_my_orders"},
    {"instruction": "주문번호 알려줘", "response": "get_my_orders"},
    {"instruction": "내가 뭐 샀는지 알려줘", "response": "get_my_orders"},
    {"instruction": "주문 내역 조회해줘", "response": "get_my_orders"},
    {"instruction": "내 구매 목록 보여줘", "response": "get_my_orders"},
    {"instruction": "지금까지 뭐 주문했어?", "response": "get_my_orders"},
    {"instruction": "주문한 상품 목록 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 확인하고 싶어", "response": "get_my_orders"},
    {"instruction": "최근에 산 것들 보여줘", "response": "get_my_orders"},
    {"instruction": "내 쇼핑 내역 보고 싶어", "response": "get_my_orders"},
    {"instruction": "주문 조회", "response": "get_my_orders"},
    {"instruction": "내 오더 보여줘", "response": "get_my_orders"},
    {"instruction": "이번 달 주문 내역 알려줘", "response": "get_my_orders"},
    {"instruction": "지난 주문 확인", "response": "get_my_orders"},
    {"instruction": "내가 주문한 상품 알려줘", "response": "get_my_orders"},
    {"instruction": "주문 목록 조회", "response": "get_my_orders"},
    {"instruction": "내 구매 이력 보여줘", "response": "get_my_orders"},
    {"instruction": "어떤 상품 주문했는지 보여줘", "response": "get_my_orders"},
    {"instruction": "내 장바구니 구매 내역 알려줘", "response": "get_my_orders"},
    {"instruction": "주문한 거 언제 오는지 알고 싶어", "response": "get_my_orders"},
    {"instruction": "배송 중인 주문 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 리스트 뽑아줘", "response": "get_my_orders"},
    {"instruction": "최신 주문 내역 확인해줘", "response": "get_my_orders"},
    {"instruction": "내가 결제한 상품 목록 보여줘", "response": "get_my_orders"},
    {"instruction": "결제 내역 알려줘", "response": "get_my_orders"},
    {"instruction": "내 구매 기록 보여줘", "response": "get_my_orders"},
    {"instruction": "주문 정보 알려줘", "response": "get_my_orders"},
    {"instruction": "내가 구매한 상품 리스트 알려줘", "response": "get_my_orders"},
    {"instruction": "주문 현황 알려줘", "response": "get_my_orders"},
    {"instruction": "내 쇼핑 목록", "response": "get_my_orders"},
    {"instruction": "구매 목록 조회해줘", "response": "get_my_orders"},
    {"instruction": "내 주문 몇 개야?", "response": "get_my_orders"},
    {"instruction": "주문한 것들 리스트 보여줘", "response": "get_my_orders"},
    {"instruction": "내가 산 상품들 뭐야?", "response": "get_my_orders"},
    {"instruction": "주문 이력 보여줘", "response": "get_my_orders"},
    {"instruction": "내 결제 목록 알려줘", "response": "get_my_orders"},
    {"instruction": "오늘 주문한 거 있어?", "response": "get_my_orders"},
    {"instruction": "주문 수량 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 날짜 알고 싶어", "response": "get_my_orders"},
    {"instruction": "언제 주문했는지 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 상품ID 뭐야?", "response": "get_my_orders"},
    {"instruction": "지금까지 얼마나 주문했어?", "response": "get_my_orders"},
    {"instruction": "내 주문 내역 전체 보여줘", "response": "get_my_orders"},
    {"instruction": "구매한 제품 목록 조회", "response": "get_my_orders"},
    {"instruction": "내 order 확인해줘", "response": "get_my_orders"},
    {"instruction": "내 쇼핑 히스토리 알려줘", "response": "get_my_orders"},
    {"instruction": "지금까지 구매한 상품 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 기록 보여줘", "response": "get_my_orders"},
    {"instruction": "주문 완료된 것들 알려줘", "response": "get_my_orders"},
    {"instruction": "내가 주문 몇 번 했어?", "response": "get_my_orders"},
    {"instruction": "가장 최근 주문이 뭐야?", "response": "get_my_orders"},
    {"instruction": "내 주문 상품 이름 알려줘", "response": "get_my_orders"},
    {"instruction": "주문 내용 보고 싶어", "response": "get_my_orders"},
    {"instruction": "내 쇼핑 내역 조회해줘", "response": "get_my_orders"},
    {"instruction": "내 구매 상품 조회", "response": "get_my_orders"},
    {"instruction": "내가 뭘 샀는지 보고 싶어", "response": "get_my_orders"},
    {"instruction": "주문 상세 알려줘", "response": "get_my_orders"},
    {"instruction": "내 주문 총 개수", "response": "get_my_orders"},
    {"instruction": "지난 구매 목록", "response": "get_my_orders"},
    {"instruction": "내 쇼핑 기록 확인", "response": "get_my_orders"},
    {"instruction": "주문 목록 불러와줘", "response": "get_my_orders"},
    {"instruction": "내가 주문한 날짜 알려줘", "response": "get_my_orders"},
    {"instruction": "내 order list 보여줘", "response": "get_my_orders"},
    {"instruction": "내 주문 내역 출력해줘", "response": "get_my_orders"},
    {"instruction": "내가 구입한 것들 알려줘", "response": "get_my_orders"},
    {"instruction": "구매 이력 조회", "response": "get_my_orders"},
    {"instruction": "내 구매 확인해줘", "response": "get_my_orders"},
    {"instruction": "내 주문 어디까지 왔어?", "response": "get_my_orders"},
    {"instruction": "내 상품 주문 내역 보여줘", "response": "get_my_orders"},
    {"instruction": "나 뭐 주문했어?", "response": "get_my_orders"},
    {"instruction": "내 주문 전체 목록", "response": "get_my_orders"},
    {"instruction": "주문 했던 거 보여줘", "response": "get_my_orders"},
    {"instruction": "내가 구매한 것 목록", "response": "get_my_orders"},
    {"instruction": "내 배송 현황", "response": "get_my_orders"},
    {"instruction": "주문한 상품 확인", "response": "get_my_orders"},
    {"instruction": "내 구매 내역 조회", "response": "get_my_orders"},
    {"instruction": "내 주문 내역 리스트", "response": "get_my_orders"},
    {"instruction": "최근 구매한 것들 보여줘", "response": "get_my_orders"},

    # ── get_my_profile ───────────────────────────────────────────
    {"instruction": "내 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "마이페이지 열어줘", "response": "get_my_profile"},
    {"instruction": "내 계정 정보 알려줘", "response": "get_my_profile"},
    {"instruction": "내 이메일 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 이름이 뭐로 등록돼 있어?", "response": "get_my_profile"},
    {"instruction": "회원 정보 확인하고 싶어", "response": "get_my_profile"},
    {"instruction": "내 프로필 보여줘", "response": "get_my_profile"},
    {"instruction": "내 회원정보 알려줘", "response": "get_my_profile"},
    {"instruction": "내 아이디 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 계정 확인해줘", "response": "get_my_profile"},
    {"instruction": "내 회원번호 알려줘", "response": "get_my_profile"},
    {"instruction": "내 개인정보 보고 싶어", "response": "get_my_profile"},
    {"instruction": "마이 페이지 보여줘", "response": "get_my_profile"},
    {"instruction": "내 정보 조회해줘", "response": "get_my_profile"},
    {"instruction": "내 프로필 정보 알려줘", "response": "get_my_profile"},
    {"instruction": "나 어떤 회원이야?", "response": "get_my_profile"},
    {"instruction": "내 계정에 등록된 정보 알려줘", "response": "get_my_profile"},
    {"instruction": "내 가입 정보 알려줘", "response": "get_my_profile"},
    {"instruction": "회원 정보 조회", "response": "get_my_profile"},
    {"instruction": "내 정보 확인", "response": "get_my_profile"},
    {"instruction": "내 나이 어떻게 돼 있어?", "response": "get_my_profile"},
    {"instruction": "내 계정 이메일 알려줘", "response": "get_my_profile"},
    {"instruction": "내가 등록한 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "내 회원 정보 수정하려고 보고 싶어", "response": "get_my_profile"},
    {"instruction": "내 정보 뭐야?", "response": "get_my_profile"},
    {"instruction": "프로필 조회해줘", "response": "get_my_profile"},
    {"instruction": "내 계정 이름 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 회원 정보 보고 싶어", "response": "get_my_profile"},
    {"instruction": "내 계정 상태 알려줘", "response": "get_my_profile"},
    {"instruction": "내 정보 페이지 보여줘", "response": "get_my_profile"},
    {"instruction": "내 가입 이메일이 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 회원 ID 알려줘", "response": "get_my_profile"},
    {"instruction": "내 account 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "내 개인 정보 조회", "response": "get_my_profile"},
    {"instruction": "나 회원 정보가 어떻게 돼 있어?", "response": "get_my_profile"},
    {"instruction": "내 등록 정보 확인해줘", "response": "get_my_profile"},
    {"instruction": "내 성함이 뭐로 등록됐어?", "response": "get_my_profile"},
    {"instruction": "회원 ID 알려줘", "response": "get_my_profile"},
    {"instruction": "내 계정 정보 불러와줘", "response": "get_my_profile"},
    {"instruction": "내 가입 정보 확인", "response": "get_my_profile"},
    {"instruction": "내 정보 출력해줘", "response": "get_my_profile"},
    {"instruction": "나의 계정 알려줘", "response": "get_my_profile"},
    {"instruction": "내 profile 보여줘", "response": "get_my_profile"},
    {"instruction": "내 개인정보 확인", "response": "get_my_profile"},
    {"instruction": "내 이메일 주소 알려줘", "response": "get_my_profile"},
    {"instruction": "내 회원 번호 몇 번이야?", "response": "get_my_profile"},
    {"instruction": "나 누구야?", "response": "get_my_profile"},
    {"instruction": "내 계정 뭐라고 돼 있어?", "response": "get_my_profile"},
    {"instruction": "나의 정보를 알려줘", "response": "get_my_profile"},
    {"instruction": "내 마이페이지 정보 조회", "response": "get_my_profile"},
    {"instruction": "내 유저 정보 알려줘", "response": "get_my_profile"},
    {"instruction": "내 사용자 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "내 로그인 이메일 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 계정에 무슨 정보 있어?", "response": "get_my_profile"},
    {"instruction": "내 회원 정보 출력해줘", "response": "get_my_profile"},
    {"instruction": "내 닉네임 뭐야?", "response": "get_my_profile"},
    {"instruction": "내 개인 계정 정보", "response": "get_my_profile"},
    {"instruction": "회원 정보 보기", "response": "get_my_profile"},
    {"instruction": "내 정보 리스트 알려줘", "response": "get_my_profile"},
    {"instruction": "내 회원 정보 리스트", "response": "get_my_profile"},
    {"instruction": "내 나이 몇살로 등록됐어?", "response": "get_my_profile"},
    {"instruction": "내 계정 조회", "response": "get_my_profile"},
    {"instruction": "내 회원 등급 알려줘", "response": "get_my_profile"},
    {"instruction": "내 회원정보 전체 보여줘", "response": "get_my_profile"},
    {"instruction": "내 개인 정보 불러와줘", "response": "get_my_profile"},
    {"instruction": "내 정보 다 알려줘", "response": "get_my_profile"},
    {"instruction": "내 account 확인해줘", "response": "get_my_profile"},
    {"instruction": "내 계정 세부 정보", "response": "get_my_profile"},
    {"instruction": "내 사용자 계정 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "내 info 알려줘", "response": "get_my_profile"},
    {"instruction": "내 가입 정보 보고 싶어", "response": "get_my_profile"},
    {"instruction": "내 이름 확인하고 싶어", "response": "get_my_profile"},
    {"instruction": "내 회원 정보 알고 싶어", "response": "get_my_profile"},
    {"instruction": "내 계정 이름 알려줘", "response": "get_my_profile"},
    {"instruction": "나의 프로필 조회", "response": "get_my_profile"},
    {"instruction": "내 정보 갱신됐는지 보여줘", "response": "get_my_profile"},
    {"instruction": "내 회원 계정 확인", "response": "get_my_profile"},
    {"instruction": "내 사용자 정보 조회", "response": "get_my_profile"},
    {"instruction": "회원가입할 때 넣은 정보 보여줘", "response": "get_my_profile"},
    {"instruction": "내 정보 현황 알려줘", "response": "get_my_profile"},
    {"instruction": "내 회원 프로필 보여줘", "response": "get_my_profile"},
    {"instruction": "내 개인 정보 열람", "response": "get_my_profile"},

    # ── get_policy ───────────────────────────────────────────────
    {"instruction": "환불 어떻게 해?", "response": "get_policy"},
    {"instruction": "교환 정책 알려줘", "response": "get_policy"},
    {"instruction": "배송 얼마나 걸려?", "response": "get_policy"},
    {"instruction": "반품 가능해?", "response": "get_policy"},
    {"instruction": "배송비 얼마야?", "response": "get_policy"},
    {"instruction": "교환 기간이 어떻게 돼?", "response": "get_policy"},
    {"instruction": "환불 기간은?", "response": "get_policy"},
    {"instruction": "반품 방법 알려줘", "response": "get_policy"},
    {"instruction": "환불 정책 알려줘", "response": "get_policy"},
    {"instruction": "배송 정책이 어떻게 돼?", "response": "get_policy"},
    {"instruction": "교환 신청 어떻게 해?", "response": "get_policy"},
    {"instruction": "반품 기간이 얼마야?", "response": "get_policy"},
    {"instruction": "무료 배송 기준이 뭐야?", "response": "get_policy"},
    {"instruction": "환불받으려면 어떻게 해?", "response": "get_policy"},
    {"instruction": "배송 언제 돼?", "response": "get_policy"},
    {"instruction": "교환하고 싶어 어떻게 해?", "response": "get_policy"},
    {"instruction": "반품 신청은 어디서 해?", "response": "get_policy"},
    {"instruction": "환불 얼마나 걸려?", "response": "get_policy"},
    {"instruction": "배송비 무료 조건이 뭐야?", "response": "get_policy"},
    {"instruction": "사이즈 교환 가능해?", "response": "get_policy"},
    {"instruction": "상품이 마음에 안 들면 환불 돼?", "response": "get_policy"},
    {"instruction": "파손된 상품 받으면 어떻게 해?", "response": "get_policy"},
    {"instruction": "오배송 받으면 어떻게 해?", "response": "get_policy"},
    {"instruction": "환불 조건이 어떻게 돼?", "response": "get_policy"},
    {"instruction": "빠른 배송 가능해?", "response": "get_policy"},
    {"instruction": "당일 배송 되나요?", "response": "get_policy"},
    {"instruction": "반품 비용은 누가 내?", "response": "get_policy"},
    {"instruction": "교환 비용은?", "response": "get_policy"},
    {"instruction": "환불 방법 알려줘", "response": "get_policy"},
    {"instruction": "배송 추적 어떻게 해?", "response": "get_policy"},
    {"instruction": "익일 배송 가능한가요?", "response": "get_policy"},
    {"instruction": "상품 하자 있으면 어떻게 해?", "response": "get_policy"},
    {"instruction": "배송 지연되면 어떻게 해?", "response": "get_policy"},
    {"instruction": "환불 신청 기간이 어떻게 돼?", "response": "get_policy"},
    {"instruction": "교환 불가 상품이 있어?", "response": "get_policy"},
    {"instruction": "반품 불가 상품은?", "response": "get_policy"},
    {"instruction": "해외 배송 되나요?", "response": "get_policy"},
    {"instruction": "배송 국가는 어디까지야?", "response": "get_policy"},
    {"instruction": "환불 수수료 있어?", "response": "get_policy"},
    {"instruction": "쿠폰 사용하면 환불이 어떻게 돼?", "response": "get_policy"},
    {"instruction": "카드 결제 취소는 얼마나 걸려?", "response": "get_policy"},
    {"instruction": "환불 계좌 등록은 어떻게 해?", "response": "get_policy"},
    {"instruction": "부분 환불 가능해?", "response": "get_policy"},
    {"instruction": "여러 상품 중 하나만 반품 가능해?", "response": "get_policy"},
    {"instruction": "배송 중에 취소 가능해?", "response": "get_policy"},
    {"instruction": "주문 취소하면 언제 환불돼?", "response": "get_policy"},
    {"instruction": "교환하면 배송비 누가 내?", "response": "get_policy"},
    {"instruction": "무료 반품 조건이 뭐야?", "response": "get_policy"},
    {"instruction": "환불 상태 어떻게 확인해?", "response": "get_policy"},
    {"instruction": "배송 보험 있어?", "response": "get_policy"},
    {"instruction": "상품 도착 전 취소 가능해?", "response": "get_policy"},
    {"instruction": "개봉한 상품 환불 돼?", "response": "get_policy"},
    {"instruction": "사용한 상품 교환 가능해?", "response": "get_policy"},
    {"instruction": "색상 교환은 어떻게 해?", "response": "get_policy"},
    {"instruction": "환불 정책 전체 알려줘", "response": "get_policy"},
    {"instruction": "배송 관련 정책 알려줘", "response": "get_policy"},
    {"instruction": "교환 반품 정책 알려줘", "response": "get_policy"},
    {"instruction": "구매 취소 어떻게 해?", "response": "get_policy"},
    {"instruction": "결제 취소 방법 알려줘", "response": "get_policy"},
    {"instruction": "상품 교환 절차 알려줘", "response": "get_policy"},
    {"instruction": "반품 절차 알려줘", "response": "get_policy"},
    {"instruction": "환불 절차 알려줘", "response": "get_policy"},
    {"instruction": "배달 기간 얼마나 걸려?", "response": "get_policy"},
    {"instruction": "묶음 배송 가능해?", "response": "get_policy"},
    {"instruction": "배송지 변경 가능해?", "response": "get_policy"},
    {"instruction": "선물 포장 가능해?", "response": "get_policy"},
    {"instruction": "배송 중 분실되면 어떻게 해?", "response": "get_policy"},
    {"instruction": "재배송 요청 가능해?", "response": "get_policy"},
    {"instruction": "환불 거절 조건이 뭐야?", "response": "get_policy"},
    {"instruction": "정품 보증 정책 알려줘", "response": "get_policy"},
    {"instruction": "AS 정책은 어떻게 돼?", "response": "get_policy"},
    {"instruction": "품절 상품 재입고 정책은?", "response": "get_policy"},
    {"instruction": "반품 택배사 어디야?", "response": "get_policy"},
    {"instruction": "교환 신청 기간은?", "response": "get_policy"},
    {"instruction": "주말 배송 돼?", "response": "get_policy"},
    {"instruction": "공휴일에도 배송해?", "response": "get_policy"},
    {"instruction": "배송비 기준 알려줘", "response": "get_policy"},
    {"instruction": "반품 주소 알려줘", "response": "get_policy"},
    {"instruction": "환불금 언제 들어와?", "response": "get_policy"},
    {"instruction": "구매 확정 후 환불 가능해?", "response": "get_policy"},
    {"instruction": "환불 규정 알려줘", "response": "get_policy"},
    {"instruction": "교환 규정 알려줘", "response": "get_policy"},
    {"instruction": "반품 규정 알려줘", "response": "get_policy"},
    {"instruction": "배송 정책 전체 알려줘", "response": "get_policy"},
    {"instruction": "교환 가능 기간은?", "response": "get_policy"},
    {"instruction": "세금계산서 발행 가능해?", "response": "get_policy"},
    {"instruction": "영수증 발급 어떻게 해?", "response": "get_policy"},
    {"instruction": "포인트 환불 정책은?", "response": "get_policy"},
    {"instruction": "적립금 환불 어떻게 돼?", "response": "get_policy"},
    {"instruction": "반품 가능 조건이 뭐야?", "response": "get_policy"},
]


# 데이터 양 불리기
augmented = []
for i in range(3):  # 약 250 * 3 = 750 samples
    for ex in examples:
        augmented.append(ex)

with open("train_classification.jsonl", "w", encoding="utf-8") as f:
    for row in augmented:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print(f"학습 데이터 저장 완료: {len(augmented)}개 (고유 샘플 {len(examples)}개 x 3배 증강)")
